### ISSUE TITLE
Limitations of Python

### ISSUE THREAD

**Issue by ruidazeng** [CianLR/kattis-solutions#2]
I am also an avid Python programmer and I write most of my solutions for online judges in Python as well. However, gradually I have encountered some problems that seem to be unsolvable in Python (including TLE's) which forced me to start learning C++. (For example, Kattis generously provided some metadata on problems, and for some problems, not a single Python solution was accepted). 

Have you encountered similar problems? How do you deal with problems that are not solvable in Python.

**Comment by CianLR** [comment]
Hi Ruida, I find the vast majority of problems are solveable in Python, just sometimes it takes some care to ensure the Python you're writing is performant. 

For example to create a list of size N the code
```
l = []
for i in range(N):
  l.append(0)
```
is a great deal slower than `l = [0] * N`.

Being aware of these pitfalls will often increase the efficiency of a Python solutions enough to bring it over the line. You are right through, sometimes C++ is the only answer, this is my fallback when Python is too slow. I find I'm not able to write a C++ solution as quickly as I would Python but presuming I have the correct algorithm it is more likely to succeed.
